#!/usr/bin/env bash
SCRIPT_DIR="$(cd -P -- "$(dirname -- "$0")" && pwd -P)"
. $SCRIPT_DIR/.addonenv.sh

EXECUTABLE="`basename $0`"

if [ "$HELP" == "true" ]; then
cat <<EOF

NAME
   $EXECUTABLE - Initialize Docker cluster environment

SYNOPSIS
   ./$EXECUTABLE [-?]

DESCRIPTION
   Initializes the Docker cluster environment as follows:

   - Copy hazelcast.xml to the '$HAZELCAST_DOCKER_CLUSTER' docker cluster
   - Create the 'nw' database in MySQL

DEFAULT
   ./$EXECUTABLE

EOF
exit
fi

# Copy hazelcast.xml to the Hazelcast cluster. It includes co-located data configuration
# for the nw/orders map. Power BI files are located in etc/powerbi/ for generating
# reports using the co-located data.
echo ""
if [ -d $PADOGRID_WORKSPACE/docker/$HAZELCAST_DOCKER_CLUSTER ]; then
   cp ../padogrid/etc/hazelcast.xml $PADOGRID_WORKSPACE/docker/$HAZELCAST_DOCKER_CLUSTER/padogrid/etc/hazelcast.xml
   echo "Copied hazelcast.xml to the $HAZELCAST_DOCKER_CLUSTER docker cluster."
else
   echo "Failed to copy 'hazelcast.xml' to the '$HAZELCAST_DOCKER_CLUSTER' docker cluster because it does not exist."
   echo "This file configures Hazelcast with co-located data. If you want to co-locate data then either"
   echo "create a docker cluster named, '$HAZELCAST_DOCKER_CLUSTER', or copy the provided 'hazelcast.xml' file to"
   echo "your Hazelcast docker cluster as follows:"
   echo ""
   echo "   cp ../padogrid/etc/hazelcast.xml \$PADOGRID_WORKSPACE/docker/<hazelcast>/padogrid/etc/"
echo ""
fi

# Create nw database and grant all permissions to the user debezium
docker exec -e MYSQL_PWD=debezium -it mysql /bin/bash -c \
"mysql -uroot -e \"GRANT ALL PRIVILEGES ON nw.* TO 'debezium'@'%'; CREATE DATABASE IF NOT EXISTS nw;\""
echo "nw database created."
echo ""

