#!/usr/bin/env bash
SCRIPT_DIR="$(cd -P -- "$(dirname -- "$0")" && pwd -P)"
. $SCRIPT_DIR/.addonenv.sh

EXECUTABLE="`basename $0`"

if [ "$HELP" == "true" ]; then
cat <<EOF

NAME
   $EXECUTABLE - Register the 'customers' Kafka connector

SYNOPSIS
   ./$EXECUTABLE [-?]

DESCRIPTION
   Registers the 'customers' Kafka connector.

DEFAULT
   ./$EXECUTABLE

EOF
exit
fi

curl -X POST -H "Content-Type: application/json" -d @connector-data-customers.json http://localhost:8083/connectors
echo
