#!/usr/bin/env bash
SCRIPT_DIR="$(cd -P -- "$(dirname -- "$0")" && pwd -P)"
. $SCRIPT_DIR/.addonenv.sh

EXECUTABLE="`basename $0`"

if [ "$HELP" == "true" ]; then
cat <<EOF

NAME
   $EXECUTABLE - Register the 'mysql' Kafka connector

SYNOPSIS
   ./$EXECUTABLE [-?]

DESCRIPTION
   Registers the 'mysql' Kafka connector.

DEFAULT
   ./$EXECUTABLE

EOF
exit
fi

curl -i -X POST -H "Accept:application/json" -H "Content-Type:application/json" localhost:8083/connectors/ -d @connector-mysql.json
echo
