#!/usr/bin/env bash
SCRIPT_DIR="$(cd -P -- "$(dirname -- "$0")" && pwd -P)"
. $SCRIPT_DIR/.addonenv.sh

EXECUTABLE="`basename $0`"

if [ "$HELP" == "true" ]; then
cat <<EOF

NAME
   $EXECUTABLE - Run MySQL CLI

SYNOPSIS
   ./$EXECUTABLE [-?]

DESCRIPTION
   Runs MySQL CLI.

DEFAULT
   ./$EXECUTABLE

EOF
exit
fi

docker exec -e MYSQL_PWD=debezium -it mysql /bin/bash -c "mysql -uroot"
