#!/usr/bin/env bash
SCRIPT_DIR="$(cd -P -- "$(dirname -- "$0")" && pwd -P)"
. $SCRIPT_DIR/.addonenv.sh

EXECUTABLE="`basename $0`"
PORT=8443

if [ "$HELP" == "true" ]; then
cat <<EOF

NAME
   $EXECUTABLE - Start NiFi container

SYNOPSIS
   ./$EXECUTABLE [-?]

DESCRIPTION
   Starts NiFi container on port $PORT.

DEFAULT
   ./$EXECUTABLE

EOF
exit
fi


if [ ! -d $APP_DIR/padogrid/nifi/data ]; then
  mkdir -p $APP_DIR/padogrid/nifi/data/avro
fi
docker run --rm -d --name nifi -p $PORT:8443 \
  --network debezium_cp_default \
  --volume $APP_DIR/padogrid:/padogrid/ \
  apache/nifi:latest

echo "NiFi container started. This may take some time to start."
echo "      URL: http://localhost:$PORT/nifi/"
echo "Templates: ../etc/nifi"
