#!/usr/bin/env bash
SCRIPT_DIR="$(cd -P -- "$(dirname -- "$0")" && pwd -P)"
. $SCRIPT_DIR/.addonenv.sh

EXECUTABLE="`basename $0`"

if [ "$HELP" == "true" ]; then
cat <<EOF

NAME
   $EXECUTABLE - Watch the specified Kafka topic

SYNOPSIS
   ./$EXECUTABLE [-?]

DESCRIPTION
   Watches the specified Kafka topic.

DEFAULT
   ./$EXECUTABLE

EXAMPLES
   ./$EXECUTABLE dbserver1.nw.customers
   ./$EXECUTABLE dbserver1.nw.orders

EOF
exit
fi

if [ "$1" == "" ]; then
   echo >&2 "ERROR: Topic is not specified. Command aborted."
   exit 1
fi

docker run --rm --tty --network debezium_cp_default confluentinc/cp-kafkacat kafkacat -b broker:29092 -t $1
